spring.application.name=agenda_java_spring
spring.datasource.url=jdbc:mysql://localhost:3306/agenda_empresa_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring-boot-starter-web=true
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.com.nluna.agenda_java_spring=INFO
